	.text
	.align 3

L149170:
	.8byte 0x408F400000000000

L14cd9c:
	.4byte o_unimplemented - L14cd9c
	.4byte o_unimplemented - L14cd9c
	.4byte o_unimplemented - L14cd9c
	.4byte o_unimplemented - L14cd9c
	.4byte o_unimplemented - L14cd9c
	.4byte o_unimplemented - L14cd9c
L14d6d8:
	.4byte o_unimplemented - L14d6d8
	.4byte o_unimplemented - L14d6d8
	.4byte o_unimplemented - L14d6d8
	.4byte o_unimplemented - L14d6d8
	.4byte o_unimplemented - L14d6d8
	.4byte o_unimplemented - L14d6d8
	.4byte o_unimplemented - L14d6d8
L14d6f4:
	.4byte o_unimplemented - L14d6f4
	.4byte o_unimplemented - L14d6f4
	.4byte o_unimplemented - L14d6f4
	.4byte o_unimplemented - L14d6f4
	.4byte o_unimplemented - L14d6f4
	.4byte o_unimplemented - L14d6f4
	.4byte o_unimplemented - L14d6f4
	.4byte o_unimplemented - L14d6f4
L14d714:
	.4byte o_unimplemented - L14d714
	.4byte o_unimplemented - L14d714
	.4byte o_unimplemented - L14d714
	.4byte o_unimplemented - L14d714
	.4byte o_unimplemented - L14d714
	.4byte o_unimplemented - L14d714
	.4byte o_unimplemented - L14d714
L14dde2:
	.8byte 0x2064696C61766E69
	.8byte 0x6172742072657375
	.8byte 0x70206D726F66736E
	.4byte 0x6C657869
	.byte  0x20
	.align 3
L14dedc:
	.8byte 0x1010101001010101
	.8byte 0x4444444411111111
	.8byte 0xAAAAAAAA55555555
	.8byte 0x300030000030003
	.8byte 0x3030303003030303
	.8byte 0xCCCCCCCC33333333
	.8byte 0xF00000000000F
	.8byte 0xF000F00000F000F
	.8byte 0xF0F0F0F00F0F0F0F
	.8byte 0x808080880808080
	.8byte 0x2222222288888888
	.8byte 0x55555555AAAAAAAA
	.8byte 0xC000C00000C000C0
	.8byte 0xC0C0C0CC0C0C0C0
	.8byte 0x33333333CCCCCCCC
	.8byte 0xF00000000000F0
	.8byte 0xF000F00000F000F0
	.8byte 0xF0F0F0FF0F0F0F0
L14df6c:
	.8byte 0xCCCCCCCCF0F0F0F0
	.8byte 0xFF00FF00AAAAAAAA
	.8byte 0xCCCCCCCCF0F0F0F0
	.8byte 0xFF00FF00FFFF0000
	.8byte 0xF0F0F0FF0F0F0F0
	.8byte 0x5555555533333333
	.8byte 0xF0F0F0FFF00FF00
	.8byte 0xFFFF000033333333
	.8byte 0xF0F0F0FFF00FF00

L14a59e:
	.string "1.2.3"
L14dfd0:
	.byte 0, 0, 4, 0, 2, 0, 1
L14dfd7:
	.byte 8, 8, 8, 4, 4, 2, 2
L14dfde:
	.byte 0, 4, 0, 2, 0, 1, 0
L14dfe5:
	.byte 8, 8, 4, 4, 2, 2, 1
L14b494:
	.string "1.6.17"

L14b49b:
L14b721:
L14b744:
L14b763:
L14bcc4:
L14bce0:
L14bcfc:
L14bd23:
L14bd40:
L14bd5d:
L14bd85:
L14bd9f:
L14bdba:
L14bdeb:
L14be0c:
L14be2f:
L14be60:
L14be7e:
L14be9c:
L14ca10:
L14ca2f:
L14ca6b:
L14cada:
L14cb92:
L14cba1:
L14cbc8:
L14cbe1:
L14cbfa:
L14cd1d:
L14ce28:
L14ce62:
L14cebd:
L14ced5:
L14ce9c:
L14cf04:
L14cf45:
L14cf6e:
L14d627:
L14d64d:
L14d74f:
L14d8dd:
L14d912:
L14d930:
L14d951:
L14d961:
L14d973:
L14d99a:
L14d9be:
L14da31:
L14da56:
L14da78:
L14da85:
L14dd79:
L14dd8c:
L14dda5:
L14ddc9:
L14de05:
L14de1b:
L14de31:
L14de45:
L14de72:
L14de93:
	.string "error"

	.align 3
L7a6bc:
L7f96c:
L7fa28:
L7fab8:
L7fc8c:
L7fd04:
png_app_error:
png_benign_error:
png_build_gamma_table:
png_calloc:
png_chunk_benign_error:
png_chunk_error:
png_chunk_warning:
png_colorspace_set_rgb_coefficients:
png_default_read_data:
png_do_bgr:
png_do_check_palette_indexes:
png_do_invert:
png_do_packswap:
png_do_read_interlace:
png_do_strip_channel:
png_do_swap:
png_error:
png_gamma_8bit_correct:
png_gamma_correct:
png_handle_bKGD:
png_handle_cHRM:
png_handle_gAMA:
png_handle_hIST:
png_handle_iCCP:
png_handle_iTXt:
png_handle_oFFs:
png_handle_pCAL:
png_handle_pHYs:
png_handle_PLTE:
png_handle_sBIT:
png_handle_sCAL:
png_handle_sPLT:
png_handle_sRGB:
png_handle_tEXt:
png_handle_tIME:
png_handle_tRNS:
png_handle_unknown:
png_handle_zTXt:
png_muldiv:
png_reciprocal:
png_reciprocal2:
png_safecat:
png_set_bgr:
png_set_expand_16:
png_set_gray_to_rgb:
png_set_invert_alpha:
png_set_invert_mono:
png_set_packing:
png_set_packswap:
png_set_scale_16:
png_set_shift:
png_set_strip_16:
png_set_strip_alpha:
png_set_swap_alpha:
png_set_swap:
png_warning:
png_zstream_error:
	bl o_unimplemented

	.section .data.rel.ro
	.align 3
L1ac508:
	.8byte o_unimplemented
L1ac650:
	.8byte png_zfree
L1ac6b0:
	.8byte o_unimplemented
L1ac908:
	.8byte png_read_filter_row_paeth3_neon
L1aca38:
	.8byte png_read_filter_row_up_neon
L1aca80:
	.8byte png_read_filter_row_avg3_neon
L1acaa8:
	.8byte o_unimplemented
L1acb48:
	.8byte o_unimplemented
L1acc70:
	.8byte o_unimplemented
L1acd48:
	.8byte png_read_filter_row_sub3_neon
L1ace10:
	.8byte png_zalloc
