	.text
	.align 3

LC_149170:
	.8byte 0x408F400000000000

LC_14cd9c:
	.4byte o_unimplemented - LC_14cd9c
	.4byte o_unimplemented - LC_14cd9c
	.4byte o_unimplemented - LC_14cd9c
	.4byte o_unimplemented - LC_14cd9c
	.4byte o_unimplemented - LC_14cd9c
	.4byte o_unimplemented - LC_14cd9c
LC_14d6d8:
	.4byte o_unimplemented - LC_14d6d8
	.4byte o_unimplemented - LC_14d6d8
	.4byte o_unimplemented - LC_14d6d8
	.4byte o_unimplemented - LC_14d6d8
	.4byte o_unimplemented - LC_14d6d8
	.4byte o_unimplemented - LC_14d6d8
	.4byte o_unimplemented - LC_14d6d8
LC_14d6f4:
	.4byte o_unimplemented - LC_14d6f4
	.4byte o_unimplemented - LC_14d6f4
	.4byte o_unimplemented - LC_14d6f4
	.4byte o_unimplemented - LC_14d6f4
	.4byte o_unimplemented - LC_14d6f4
	.4byte o_unimplemented - LC_14d6f4
	.4byte o_unimplemented - LC_14d6f4
	.4byte o_unimplemented - LC_14d6f4
LC_14d714:
	.4byte o_unimplemented - LC_14d714
	.4byte o_unimplemented - LC_14d714
	.4byte o_unimplemented - LC_14d714
	.4byte o_unimplemented - LC_14d714
	.4byte o_unimplemented - LC_14d714
	.4byte o_unimplemented - LC_14d714
	.4byte o_unimplemented - LC_14d714
LC_14dde2:
	.8byte 0x2064696C61766E69
	.8byte 0x6172742072657375
	.8byte 0x70206D726F66736E
	.4byte 0x6C657869
	.byte  0x20
	.align 3
LC_14dedc:
	.8byte 0x1010101001010101
	.8byte 0x4444444411111111
	.8byte 0xAAAAAAAA55555555
	.8byte 0x300030000030003
	.8byte 0x3030303003030303
	.8byte 0xCCCCCCCC33333333
	.8byte 0xF00000000000F
	.8byte 0xF000F00000F000F
	.8byte 0xF0F0F0F00F0F0F0F
	.8byte 0x808080880808080
	.8byte 0x2222222288888888
	.8byte 0x55555555AAAAAAAA
	.8byte 0xC000C00000C000C0
	.8byte 0xC0C0C0CC0C0C0C0
	.8byte 0x33333333CCCCCCCC
	.8byte 0xF00000000000F0
	.8byte 0xF000F00000F000F0
	.8byte 0xF0F0F0FF0F0F0F0
LC_14df6c:
	.8byte 0xCCCCCCCCF0F0F0F0
	.8byte 0xFF00FF00AAAAAAAA
	.8byte 0xCCCCCCCCF0F0F0F0
	.8byte 0xFF00FF00FFFF0000
	.8byte 0xF0F0F0FF0F0F0F0
	.8byte 0x5555555533333333
	.8byte 0xF0F0F0FFF00FF00
	.8byte 0xFFFF000033333333
	.8byte 0xF0F0F0FFF00FF00
LC_stack_chk_guard:
	.8byte 0x1234567890abcdef

LC_14a59e:
	.string "1.2.3"
LC_14dfd0:
	.byte 0, 0, 4, 0, 2, 0, 1
LC_14dfd7:
	.byte 8, 8, 8, 4, 4, 2, 2
LC_14dfde:
	.byte 0, 4, 0, 2, 0, 1, 0
LC_14dfe5:
	.byte 8, 8, 4, 4, 2, 2, 1
LC_14b494:
	.string "1.6.17"

LC_14b49b:
LC_14b721:
LC_14b744:
LC_14b763:
LC_14bcc4:
LC_14bce0:
LC_14bcfc:
LC_14bd23:
LC_14bd40:
LC_14bd5d:
LC_14bd85:
LC_14bd9f:
LC_14bdba:
LC_14bdeb:
LC_14be0c:
LC_14be2f:
LC_14be60:
LC_14be7e:
LC_14be9c:
LC_14ca10:
LC_14ca2f:
LC_14ca6b:
LC_14cada:
LC_14cb92:
LC_14cba1:
LC_14cbc8:
LC_14cbe1:
LC_14cbfa:
LC_14cd1d:
LC_14ce28:
LC_14ce62:
LC_14cebd:
LC_14ced5:
LC_14ce9c:
LC_14cf04:
LC_14cf45:
LC_14cf6e:
LC_14d627:
LC_14d64d:
LC_14d74f:
LC_14d8dd:
LC_14d912:
LC_14d930:
LC_14d951:
LC_14d961:
LC_14d973:
LC_14d99a:
LC_14d9be:
LC_14da31:
LC_14da56:
LC_14da78:
LC_14da85:
LC_14dd79:
LC_14dd8c:
LC_14dda5:
LC_14ddc9:
LC_14de05:
LC_14de1b:
LC_14de31:
LC_14de45:
LC_14de72:
LC_14de93:
	.string "error"

	.align 3
L7a6bc:
L7f96c:
L7fa28:
L7fab8:
L7fc8c:
L7fd04:
png_app_error:
png_benign_error:
png_build_gamma_table:
png_calloc:
png_chunk_benign_error:
png_chunk_error:
png_chunk_warning:
png_colorspace_set_rgb_coefficients:
png_default_read_data:
png_do_bgr:
png_do_check_palette_indexes:
png_do_invert:
png_do_packswap:
png_do_read_interlace:
png_do_strip_channel:
png_do_swap:
png_error:
png_gamma_8bit_correct:
png_gamma_correct:
png_handle_bKGD:
png_handle_cHRM:
png_handle_gAMA:
png_handle_hIST:
png_handle_iCCP:
png_handle_iTXt:
png_handle_oFFs:
png_handle_pCAL:
png_handle_pHYs:
png_handle_PLTE:
png_handle_sBIT:
png_handle_sCAL:
png_handle_sPLT:
png_handle_sRGB:
png_handle_tEXt:
png_handle_tIME:
png_handle_tRNS:
png_handle_unknown:
png_handle_zTXt:
png_muldiv:
png_reciprocal:
png_reciprocal2:
png_safecat:
png_set_bgr:
png_set_expand_16:
png_set_gray_to_rgb:
png_set_invert_alpha:
png_set_invert_mono:
png_set_packing:
png_set_packswap:
png_set_scale_16:
png_set_shift:
png_set_strip_16:
png_set_strip_alpha:
png_set_swap_alpha:
png_set_swap:
png_warning:
png_zstream_error:
	bl o_unimplemented

	.data.rel.ro
	.align 3
LC_1ac508:
	.8byte o_unimplemented
LC_1ac650:
	.8byte png_zfree
LC_1ac6b0:
	.8byte o_unimplemented
LC_1ac730:
	.8byte o_unimplemented
LC_1ac908:
	.8byte png_read_filter_row_paeth3_neon
LC_1aca38:
	.8byte png_read_filter_row_up_neon
LC_1aca80:
	.8byte png_read_filter_row_avg3_neon
LC_1acaa8:
	.8byte o_unimplemented
LC_1acb48:
	.8byte o_unimplemented
LC_1acb60:
	.8byte LC_stack_chk_guard
LC_1acc70:
	.8byte o_unimplemented
LC_1acd48:
	.8byte png_read_filter_row_sub3_neon
LC_1ace10:
	.8byte png_zalloc
