#!/bin/bash

adb push ./libs/arm64-v8a/ututna /data/local/tmp/
adb shell chmod +x /data/local/tmp/ututna

while true; do
  case "$1" in
  --loop) loop=$2; shift 2;;
  *) break;;
  esac
done

if [[ ! $loop ]]; then
  adb shell "cd /data/local/tmp/; taskset 80 ./ututna $@"
else
  for ((i=1; i<=$loop; i++)); do
    adb shell "cd /data/local/tmp/; taskset 80 ./ututna $@"
  done
fi
