#!/bin/bash

[ -z "$ANDROID_NDK_HOME" ] && echo "ANDROID_NDK_HOME is not set" && exit 1
[ ! -f libabenchmark.so ] && echo "libabenchmark.so is missing" && exit 1

OUT=out
[ ! -d $OUT ] && mkdir $OUT

TMPFILE=$OUT/~tmp.s

process() {
  echo --- $1 ---

  echo dissmebling $2...
  ../disass $2 "${@:3}" > $TMPFILE

  echo refining...
  echo -e '\t'.text > $OUT/$1
  for sym in "${@:3}"; do
    if [[ $sym == @* ]]; then
      echo -e '\t'.global ${sym:1} >> $OUT/$1
    fi
  done
  echo -e '\t'.align 3 >> $OUT/$1
  python ../refine.py $TMPFILE >> $OUT/$1

  echo post prossing...
  python ../post.py $OUT/$1

  rm $TMPFILE
}

replace() {
  if [[ `uname -s` == Darwin ]]; then
    sed -i '' "/^$2/s/$3/$4/" $OUT/$1
  else
    sed -i "/^$2/s/$3/$4/" $OUT/$1
  fi
}

replace_global() {
  if [[ `uname -s` == Darwin ]]; then
    sed -i '' "s/$2/$3/g" $OUT/$1
  else
    sed -i "s/$2/$3/g" $OUT/$1
  fi
}

LIB=libabenchmark.so

process 600_fft.s $LIB \
  @kiss_fftr_alloc kiss_fft_alloc \
  @kiss_fftr kiss_fft L56d54-574dc

process 601_gemm.s $LIB \
  @test_sgemm @_Z5sgemmjPfS_S_ _Z10sgemm_neonjPfS_S_ \
  @test_dgemm @_Z5dgemmjPdS_S_ _Z8gemm_optIdEvjPT_S1_S1_
replace_global 601_gemm.s s_malloc gemm_malloc
replace_global 601_gemm.s s_free gemm_free

process 603_map.s $LIB \
  @test_map \
  _Z16test_map_orderedd \
  _Z18test_map_unorderedd \
  ?_Z15test_const_timeR8CMapTestd \
  _ZN8CMapTestC2Ev \
  _ZN8CMapTestD2Ev \
  _ZN8CMapTest9init_testEjjj \
  _ZN8CMapTest9fini_testEv \
  _ZNSt3mapIj12SDataElementSt4lessIjESaISt4pairIKjS0_EEEixERS4_ \
  _ZNSt8_Rb_treeIjSt4pairIKj12SDataElementESt10_Select1stIS3_ESt4lessIjESaIS3_EE29_M_get_insert_hint_unique_posESt23_Rb_tree_const_iteratorIS3_ERS1_ \
  _ZN12CMapTestImplISt3mapIj12SDataElementSt4lessIjESaISt4pairIKjS1_EEESt17_Rb_tree_iteratorIS6_EE4testEPj \
  _ZN8CMapTest13shuffle_arrayEPjj \
  _ZNSt8_Rb_treeIjSt4pairIKj12SDataElementESt10_Select1stIS3_ESt4lessIjESaIS3_EE5eraseERS1_ \
  _ZNK8CMapTest16get_ops_per_testEv \
  _ZNSt8_Rb_treeIjSt4pairIKj12SDataElementESt10_Select1stIS3_ESt4lessIjESaIS3_EE8_M_eraseEPSt13_Rb_tree_nodeIS3_E \
  _ZN12CMapTestImplISt13unordered_mapIj12SDataElementSt4hashIjESt8equal_toIjESaISt4pairIKjS1_EEENSt8__detail14_Node_iteratorIS8_Lb0ELb0EEEEC2Ev \
  _ZN12CMapTestImplISt13unordered_mapIj12SDataElementSt4hashIjESt8equal_toIjESaISt4pairIKjS1_EEENSt8__detail14_Node_iteratorIS8_Lb0ELb0EEEE9init_testEjjj \
  _ZNSt10_HashtableIjSt4pairIKj12SDataElementESaIS3_ENSt8__detail10_Select1stESt8equal_toIjESt4hashIjENS5_18_Mod_range_hashingENS5_20_Default_ranged_hashENS5_20_Prime_rehash_policyENS5_17_Hashtable_traitsILb0ELb0ELb1EEEE21_M_insert_unique_nodeEmmPNS5_10_Hash_nodeIS3_Lb0EEE \
  _ZNSt10_HashtableIjSt4pairIKj12SDataElementESaIS3_ENSt8__detail10_Select1stESt8equal_toIjESt4hashIjENS5_18_Mod_range_hashingENS5_20_Default_ranged_hashENS5_20_Prime_rehash_policyENS5_17_Hashtable_traitsILb0ELb0ELb1EEEE13_M_rehash_auxEmSt17integral_constantIbLb1EE \
  _ZNSt10_HashtableIjSt4pairIKj12SDataElementESaIS3_ENSt8__detail10_Select1stESt8equal_toIjESt4hashIjENS5_18_Mod_range_hashingENS5_20_Default_ranged_hashENS5_20_Prime_rehash_policyENS5_17_Hashtable_traitsILb0ELb0ELb1EEEE6rehashEm \
  _ZN12CMapTestImplISt13unordered_mapIj12SDataElementSt4hashIjESt8equal_toIjESaISt4pairIKjS1_EEENSt8__detail14_Node_iteratorIS8_Lb0ELb0EEEE4testEPj \
  __floatsitf __extendsftf2 __multf3 __trunctfdf2 __floatunditf __divtf3 __getf2 \
  L10f608-10f7f8 L10f928-10fe94 L129290-1294e8
replace 603_map.s _ZN8CMapTestD1Ev: _ZN8CMapTestD1Ev _ZN8CMapTestD2Ev

process 609_png.s $LIB \
  @_Z10loadMemPNGPhjP7BmpData png_create_read_struct png_create_png_struct \
  png_set_mem_fn png_set_error_fn png_user_version_check png_malloc_warn \
  png_set_read_fn png_create_info_struct png_malloc_base png_set_longjmp_fn \
  png_read_png png_read_info png_read_sig png_read_data png_get_io_ptr \
  png_sig_cmp png_read_chunk_header png_reset_crc png_calculate_crc \
  png_handle_IHDR png_crc_error png_set_IHDR png_check_IHDR \
  png_chunk_unknown_handling png_set_expand png_set_interlace_handling \
  png_read_start_row png_init_read_transformations png_gamma_significant \
  png_free png_malloc png_zalloc png_read_transform_info png_free_data \
  png_read_image png_read_row png_read_IDAT_data png_do_read_transformations \
  png_combine_row png_read_finish_row png_read_filter_row \
  png_init_filter_functions_neon png_read_filter_row_sub3_neon \
  png_read_filter_row_paeth3_neon png_read_filter_row_avg3_neon \
  png_read_filter_row_up_neon png_crc_finish png_read_end \
  png_read_finish_IDAT png_handle_IEND png_get_IHDR png_get_rows \
  png_destroy_read_struct png_destroy_info_struct png_destroy_gamma_table \
  png_zfree png_destroy_png_struct png_free_jmpbuf \
  L66b18-66b8c L7a214-7a6bc L7c010-7c118
replace 609_png.s L66984: gettimeofday s_gettimeofday_begin
replace 609_png.s L66a88: gettimeofday s_gettimeofday_end

process 614_physics.s $LIB \
  @test_physics cpSpaceNew cpSpaceInit cpBBTreeNew cpSpatialIndexInit \
  cpHashSetNew cpArrayNew cpBBTreeSetVelocityFunc cpBodyInit cpBodySetMass \
  cpBodyActivate cpBodyGetType cpBodySetType cpSpaceSetIterations \
  cpSpaceUseSpatialHash cpSpaceHashNew cpHashSetEach cpSpatialIndexFree \
  cpHashSetFree cpArrayFreeEach cpArrayFree cpBodyNew cpBodySetPosition \
  cpCircleShapeNew cpMomentForCircle cpAreaForCircle cpShapeSetElasticity \
  cpShapeSetFriction cpShapeGetBody cpSpaceAddBody cpArrayPush cpSpaceAddShape \
  cpBodyAddShape cpShapeUpdate cpHashSetInsert cpArrayPop cpBodySetVelocity \
  cpShapeSetFilter cpSpaceStep cpShapeGetBB cpBodyUpdatePosition \
  cpSpacePushFreshContactBuffer cpShapeUpdateFunc cpShapeCacheBB \
  cpSpaceCollideShapes cpSpatialIndexCollideStatic cpHashSetCount \
  cpSpaceProcessComponents cpHashSetFilter cpBodyUpdateVelocity cpSpaceUnlock \
  cpCollide cpArbiterInit cpArbiterUpdate cpHashSetFind \
  cpSpaceArbiterSetFilter cpBodyIsSleeping cpArbiterPreStep \
  cpArbiterApplyCachedImpulse cpArbiterApplyImpulse cpArbiterUnthread \
  cpSpaceEachShape cpSpaceLock cpSpaceAddPostStepCallback cpSpaceRemoveShape \
  cpBodyRemoveShape cpHashSetRemove cpShapeFree cpArrayDeleteObj \
  cpSpaceEachConstraint cpSpaceEachBody cpSpaceRemoveBody cpBodyFree \
  cpSpaceFree cpSpaceDestroy \
  @StartStopwatch @StopStopwatch TicksToFracSecs \
  L8b5a0-8b5c0 L8b5e0-8b624 L8b648-8b66C L8d814-8d8b0 \
  L90058-90154 L93d88-93fd4 L9a820-9a86c L9bc4c-9bc54 \
  L9be30-9be74 L9bc54-9bc58 L9ca0c-9cad0 L9ce84-9ce8c \
  L9e7d4-9ea30 L9ebe0-9ed04 L9ed30-9edec L9ef2c-9f024 \
  L9f570-9f804 L9f838-9fb88 La0cf8-a0d78
replace 614_physics.s L8b4bc: StartStopwatch s_StartStopwatch
replace 614_physics.s L8b4f8: StopStopwatch s_StopStopwatch

process 607_hash.s $LIB \
  @generate_test_data encryption_data av_aes_init av_aes_crypt \
  @md5_sum_data av_md5_sum av_md5_update \
  @sha1_sum_data @sha2_sum_data av_sha_init av_sha_update av_sha_final \
  @crc_sum_data calc_buffer_crc \
  L4c208-4c464 L4d10c-4e064
