#!/bin/bash

[ -z "$ANDROID_NDK_HOME" ] && echo "ANDROID_NDK_HOME is not set" && exit 1
[ ! -f libabenchmark.so ] && echo "libabenchmark.so is missing" && exit 1

TMPFILE=~tmp.s

process() {
  echo --- $1 ---

  echo dissmebling $2...
  ../disass $2 "${@:3}" > $TMPFILE

  echo check missing...
  ../check_missing $TMPFILE

  echo refining...
  echo -e '\t'.text > $1.s
  echo -e '\t'.align 3 >> $1.s
  for sym in "${@:3}"; do
    if [[ $sym != *: ]]; then
      echo -e '\t'.global $sym >> $1.s
    fi
  done
  python ../refine.py $TMPFILE >> $1.s

  echo post prossing...
  python ../post.py $1.s

  rm $TMPFILE
}

replace() {
  if [[ `uname -s` == Darwin ]]; then
    sed -i '' "/^$2/s/$3/$4/" $1
  else
    sed -i "/^$2/s/$3/$4/" $1
  fi
}

LIB=libabenchmark.so

process 600.fft $LIB kiss_fftr_alloc kiss_fft_alloc kiss_fftr kiss_fft 56d54:
process 601.gemm $LIB test_sgemm _Z5sgemmjPfS_S_ _Z10sgemm_neonjPfS_S_ \
  test_dgemm _Z5dgemmjPdS_S_ _Z8gemm_optIdEvjPT_S1_S1_
