#!/bin/bash

# usage: disass [--static] elf sym1 sym2 ...

[ -z "$ANDROID_NDK_HOME" ] && echo "ANDROID_NDK_HOME is not set" && exit 1

path=$(cd `dirname $0`; pwd)

while true; do
  case "$1" in
  --static) static=1; shift;;
  *) break;;
  esac
done

elf=$1
shift

objdump=$($path/ndk-which --abi arm64-v8a objdump)

disass() {
  if [[ $static == 1 ]]; then
    sym=`$objdump -t $elf | grep -w $1 | grep -w g`
  else
    sym=`$objdump -T $elf | grep -w $1`
  fi

  if [ -n "$sym" ]; then
    start=`echo $sym | awk '{print $1}'`

    if [ $start != "0000000000000000" ]; then
      type=`echo $sym | awk '{print $4}'`
      size=`echo $sym | awk '{print $5}'`
      end=`printf "%016x\n" $((0x$start+0x$size))`
      printf '# %24s %s %s %s %s\n' "$1" "$start" "$end" "$size" "$type"

      $objdump -d $elf --start-address=0x$start --stop-address=0x$end
    fi
  fi
}

disass_loc() {
  arr=(${1//-/ })
  start=${arr[0]}
  end=${arr[1]}

  printf '# %s\n' "$start:"

  $objdump -d $elf --start-address=0x$start --stop-address=0x$end
}

for symbol in ${@}
do
  if [[ $symbol = \?* ]]; then
    continue
  elif [[ $symbol = L* ]]; then
    disass_loc ${symbol:1}
  elif [[ $symbol = @* ]]; then
    disass ${symbol:1}
  else
    disass $symbol
  fi
done
