#!/bin/bash

[ -z "$ANDROID_NDK_HOME" ] && echo "ANDROID_NDK_HOME is not set" && exit 1

elf=$1

path=$(cd `dirname $0`; pwd)

objdump=$($path/ndk-which --abi arm64-v8a objdump)

disass() {
  sym=`$objdump -T $elf | grep -w $1`

  if [ -n "$sym" ]; then
    start=`echo $sym | awk '{print $1}'`

    if [ $start != "0000000000000000" ]; then
      type=`echo $sym | awk '{print $4}'`
      size=`echo $sym | awk '{print $5}'`
      end=`printf "%016x\n" $((0x$start+0x$size))`
      printf '# %24s %s %s %s %s\n' "$1" "$start" "$end" "$size" "$type"

      $objdump -d $elf --start-address=0x$start --stop-address=0x$end
    fi
  fi
}

disass_loc() {
  printf '# %s\n' "$1:"

  $objdump -d $elf --start-address=0x$1 | sed '/ret/q'
}

for symbol in ${@:2}
do
  if [[ $symbol = *: ]]; then
    disass_loc ${symbol::${#symbol}-1}
  else
    disass $symbol
  fi
done
