#!/bin/bash

ar=$(../ndk-which --abi arm64-v8a ar)

extract() {
  if [[ ! -d $1 ]]; then
    echo extracting $1...
    mkdir $1
    cd $1
    $ar x ../$1.a
    cd ..
  fi
}

cd android-26
extract libc
extract libm
extract libz
